version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: payoova-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: payoova
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - payoova-dev-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: payoova-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/payoova?authSource=admin
      PORT: 3000
      FRONTEND_URL: http://localhost:3001
      # Add your development environment variables here
      AUTH0_DOMAIN: your-auth0-domain.auth0.com
      AUTH0_AUDIENCE: your-auth0-audience
      AUTH0_CLIENT_ID: your-auth0-client-id
      AUTH0_CLIENT_SECRET: your-auth0-client-secret
      ETHEREUM_RPC_URL: https://mainnet.infura.io/v3/your-infura-key
      POLYGON_RPC_URL: https://polygon-mainnet.infura.io/v3/your-infura-key
      ENCRYPTION_KEY: your-32-character-encryption-key
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - payoova-dev-network
    command: npm run dev

volumes:
  mongodb_dev_data:

networks:
  payoova-dev-network:
    driver: bridge
